### ISSUE TITLE
Сделать всё заебись

### ISSUE THREAD

**Issue by senaev** [Mello578/mello578.github.io#2]

**Comment by Mello578** [comment]
так

**Comment by Mello578** [comment]
говори

**Comment by senaev** [comment]
https://github.com/Mello578/mello578.github.io/blob/master/index.html#L27

тут можно присвоить айдишник кнопке, а затем навесить обработчик
```html
<button id="my-button"> Расчет </button>
<script>
const myButton = document.getElementById('my-button');
myButton.onclick = () => {
consumption();
consumption2();
}
</script>
```
так делают крутые ребята

**Comment by Mello578** [comment]
ну мне пока просто разобраться. Короче смотри, вопрос номер раз

**Comment by Mello578** [comment]
var distance2 = document.getElementById("dist2").value;
    var spent2 = document.getElementById("cpa2").value;
    consum2=spent2/distance2*100;
    alert ("А помойка лоха на 100 км жрет " + consum2 + " литров бензина");
    document.getElementById("dist2").value=0;
    document.getElementById("cpa2").value=0;

**Comment by Mello578** [comment]
я создал переменные, присвоил значения, посчитал, вывел собщения, очистил данные ввода

**Comment by senaev** [comment]
там же строковые значения, лучше делеать так
```javascript
const spent2 = parseInt(document.getElementById("cpa2").value, 10);
document.getElementById("dist2").value='';
```

**Comment by senaev** [comment]
в чем вопрос то?

**Comment by Mello578** [comment]
такая запись вобще норм ? Я сначала думал он норм будет работать если как присвоил значение, сразу поле обнулил и заебись

**Comment by Mello578** [comment]
var distance2 = document.getElementById("dist2").value=0;
var spent2 = document.getElementById("cpa2").value=0;
consum2=spent2/distance2*100;

**Comment by Mello578** [comment]
но он мне считать не успевал и выводил значение NaN, типо такого чето

**Comment by senaev** [comment]
Ну понятно, это чисто проблема типизации и алгоритма

**Comment by senaev** [comment]
Я сделал охуенный пулл-реквест, но ты, пидар, как всегда всё испортил
У меня нет доступа и я ниче не могу сделать
пропиши меня в Collaborators

**Comment by senaev** [comment]
https://github.com/Mello578/mello578.github.io/pull/3

**Comment by senaev** [comment]
@Mello578 Давай в следующей итерации заебашим то-же самое, только чтобы можно было сделать сколько угодно машин с водителями

1) Есть кнопка - добавить тачку, по ней появляются три дополнительных поля - имя, пробег расход
2) По результату получаем табличку с данными о том, у кого какой расход. Красным подсвечен самый большой расход, зеленым - самый маленький

**Comment by Mello578** [comment]
Сделал. Давай уеба проверяй
